# Netlify config file
[build]
  command = "npm run build"
  publish = ".next"
[build.environment]
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"
    # prevent progress messages
    CI = "1"

[[plugins]]
  package = "netlify-plugin-cypress"

  # let's first test the site before Next JS builds it
  [plugins.inputs.preBuild]
    enable = true
    start = 'npm run dev'
    wait-on = 'http://localhost:3000'
    wait-on-timeout = '30' # seconds
    record = true
    group = '1: testing develop site'

  # then Netlify builds the site
  # and then our tests will run again, testing the built production version
  [plugins.inputs.postBuild]
    # investigating why preBuild server has not been stopped
    enable = true
    record = true
    group = '2: testing built site'

  # but we do not want to run tests against the deployed site
  [plugins.inputs]
    enable = false