export const LOADING = 'LOADING';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const RESET = 'RESET';

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_ERROR = "GET_ALL_CATEGORIES_ERROR";

export const GET_ALL_CARTS = "GET_ALL_CARTS";
export const GET_ALL_CARTS_SUCCESS = "GET_ALL_CARTS_SUCCESS";
export const GET_ALL_CARTS_ERROR = "GET_ALL_CARTS_ERROR";

export const GET_SINGLE_CART= "GET_SINGLE_CART";
export const GET_SINGLE_CART_SUCCESS = "GET_SINGLE_CART_SUCCESS";
export const GET_SINGLE_CART_ERROR = "GET_SINGLE_CART_ERROR";
